
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dev
  password: password
  host: localhost

development:
  <<: *default
  database: loyalty_program_development
  host: localhost
  username: dev
  password: password

test:
  <<: *default
  database: loyalty_program_development
  host: localhost
  username: dev
  password: password
