default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dev
  password: password

development:
  <<: *default
  database: loyalty_program_development1
  host: localhost

test:
  <<: *default
  database: loyalty_program_test1
  host: localhost
